version: '3.4'
services:
  web:
    image: odoo16:latest
    depends_on:
      - db
    ports:
      - "8025:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./etc/config:/etc/odoo
      - ./:/mnt/extra-addons
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    networks:
      - webnet
  db:
    image: postgres:13
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - webnet
volumes:
  odoo-web-data:
  odoo-db-data:
networks:
  webnet:
